services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/ngnix.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  trade-vista-app:
    image: trade-vista:latest

    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    ports:
      - "8080:8080"
    volumes:
      - ./opt/trade-vista/transactions:/app/transactions
